version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  db-mongo:
    image: mongo
    command: --smallfiles
    ports:
      - "27017"
    volumes:
      - ./data:/data/db